go.property("energy_saving", 30)
go.property("screen_dimming", 60)
go.property("disable_rendering", 120)
go.property("max_fps", 30)
go.property("is_energy_saving_allowed", true)


local function create_timer(self, delay, enable_fn, disable_fn)
	if delay == 0 then
		return { reset = function() end }
	end
	local handle = nil
	return {
		reset = function()
			if handle then
				timer.cancel(handle)
			else
				disable_fn(self)
			end
			handle = timer.delay(delay, false, function()
				enable_fn(self)
				handle = nil
			end)
		end
	}
end

local function enable_energy_saver(self)
	sys.set_update_frequency(self.max_fps)
	print("energy saving enabled. update frequency set to", self.max_fps)
end
local function disable_energy_saver(self)
	sys.set_update_frequency(self.default_update_frequency)
	print("energy saving disabled. update frequency reset to", self.default_update_frequency)
end

local function disable_rendering(self)
	sys.set_render_enabled(false)
	print("rendering disabled")
end
local function enable_rendering(self)
	sys.set_render_enabled(true)
	print("rendering enabled")
end

local function enable_screen_dimmer(self)
	msg.post("#screen_dimmer", "enable_dimmer")
end
local function disable_screen_dimmer(self)
	msg.post("#screen_dimmer", "disable_dimmer")
end

local function reset_timers(self)
	self.energy_saver_timer.reset()
	self.disable_rendering_timer.reset()
	self.screen_dimming_timer.reset()
end

function init(self)
	msg.post(".", "acquire_input_focus")
	self.default_update_frequency = sys.get_config_int("display.update_frequency")
	self.energy_saver_timer = create_timer(self, self.energy_saving, enable_energy_saver, disable_energy_saver)
	self.disable_rendering_timer = create_timer(self, self.disable_rendering, disable_rendering, enable_rendering)
	self.screen_dimming_timer = create_timer(self, self.screen_dimming, enable_screen_dimmer, disable_screen_dimmer)
	reset_timers(self)
end

function on_input(self, action_id, action)
	reset_timers(self)
end
